version: '3.8'
services:
  # 1. The Database Service
  postgres-db:
    image: postgres:15-alpine
    container_name: ticket-booking-db
    environment:
      - POSTGRES_USER=thinh
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ticket_booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U thinh -d ticket_booking_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ticketing-network

  # 2. Redis for Distributed Locking
  redis:
    image: redis:7-alpine
    container_name: ticketing-redis
    ports:
      - "6379:6379"
    networks:
      - ticketing-network


networks:
  ticketing-network:
    driver: bridge

volumes:
  postgres-data: