server:
  port: 8085

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/payment_db
    username: thinh
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public

logging:
  pattern:
    level: "%5p [${spring.application.name:}, traceId=%X{traceId:-}, spanId=%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0 # Keep this at 100% for testing

  # explicitly disable ALL metrics export to OTLP
  otlp:
    metrics:
      export:
        enabled: false

    tracing:
      # Explicitly set the trace endpoint (do NOT use the generic management.otlp.endpoint)
      endpoint: http://localhost:4318/v1/traces
      transport: http
