server:
  port: 8082
spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/event_db
    username: thinh
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public
    locations: classpath:db/migration
    connect-retries: 10